version: '3'
services:

  cypress:
    container_name: cypress
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code
    command: /app/wait-for-it.sh localhost:3000 -t 120 -- npm run test
    ports:
      - 3000:3000
